#ifndef MSG_1_COLORS_H
#define MSG_1_COLORS_H

// autogenerated

typedef struct {
    uint16_t hdr;
    uint8_t red;
} msg1_colors_data_t;

int msg1_colors_load_net_raw(const char* const buffer, int size, msg1_colors_data_t* data);
int msg1_colors_dump_net_raw(const msg1_colors_data_t* const data, char* buffer, int size);

int msg1_colors_load_raw(const char* const buffer, int size, msg1_colors_data_t* data);
int msg1_colors_dump_raw(const msg1_colors_data_t* const data, char* buffer, int size);

#endif
